### ISSUE TITLE
where to find the data ?

### ISSUE THREAD

**Issue by ghost** [ONeillMB1/Phylogeography#1]
when I use your r code to plot, but I do not find the data, like :lin1_snps_MCC.tree,
could you please upload all the data in your scripts, thanks.

**Comment by ONeillMB1** [comment]
Hello. Please refer to this GitHub repo https://github.com/ONeillMB1/Mtb_Phylogeography
which has cleaner code and the data associated with our manuscript. It is also licensed.

**Comment by liamxg** [comment]
dear @ONeillMB1, could not find the data/Dataset1.txt in the raxml_tree.R file"
Read meta info for samples
meta <- read.table("data/Dataset1.txt", header=T, sep='\t', na.strings="NA", stringsAsFactors=FALSE)
