### ISSUE TITLE
How can I find the data in your mentioned  in your rmd files?

### ISSUE THREAD

**Issue by liamxg** [ONeillMB1/Phylogeography#2]
How can I find the data in your mentioned  in your rmd files?

**Comment by ONeillMB1** [comment]
Hello. Please refer to this GitHub repo https://github.com/ONeillMB1/Mtb_Phylogeography
 which has cleaner code and the data associated with our manuscript. It is also licensed.

**Comment by liamxg** [comment]
@ONeillMB1 thanks.
